"""
Report Generator
=================
Produces a formatted Markdown scoping report from assessment results.
The report is suitable for submission to a CMMC assessor or C3PAO
as evidence of a scoping analysis.
"""

from datetime import datetime
from pathlib import Path
from typing import Dict, Any


class ReportGenerator:
    """Generates a formatted Markdown scoping report."""

    def __init__(self, metadata: Dict, responses: Dict, score: Dict):
        self.meta      = metadata
        self.responses = responses
        self.score     = score
        self.flat: Dict[str, Any] = {}
        for module_data in responses.values():
            if isinstance(module_data, dict):
                self.flat.update(module_data)

    def generate_markdown(self) -> str:
        date_str = datetime.now().strftime("%B %d, %Y")
        org      = self.meta.get("organization", "[Organization Name]")
        assessor = self.meta.get("assessor",     "[Assessor Name]")
        cage     = self.meta.get("cage_code") or "N/A"
        contract = self.meta.get("contract_ref") or "N/A"

        score    = self.score
        cui      = score.get("cui_in_scope", False)
        fci      = score.get("fci_in_scope", False)
        level    = score.get("cmmc_level_required", "Unknown")
        systems  = score.get("systems_in_scope", "Unknown")
        enclave  = score.get("enclave_recommended", False)
        gaps     = score.get("compliance_gaps", [])
        hi_gaps  = score.get("high_priority_gaps", [])
        ctrl_gaps= score.get("nist_control_gaps", [])
        reduce   = score.get("scope_reduction_possible", False)

        lines = []

        # ── Cover ──────────────────────────────────────────────────────────────
        lines += [
            "# CMMC CUI/FCI Scoping Assessment Report",
            "",
            f"**Organization:** {org}",
            f"**CAGE Code:** {cage}",
            f"**Primary Contract Reference:** {contract}",
            f"**Assessment Completed By:** {assessor}",
            f"**Assessment Date:** {date_str}",
            f"**Tool:** CMMC Enclave Toolkit v1.0.0 — github.com/yourusername/cmmc-enclave-toolkit",
            "",
            "---",
            "",
            "> ⚠️ **Disclaimer:** This report is generated by a self-assessment tool and does not constitute",
            "> a formal CMMC assessment. It is intended as a gap analysis and scoping preparation tool.",
            "> Organizations must obtain certification from a Certified Third-Party Assessment Organization",
            "> (C3PAO) for official CMMC Level 2 certification.",
            "",
            "---",
            "",
        ]

        # ── Executive Summary ──────────────────────────────────────────────────
        lines += [
            "## Executive Summary",
            "",
            "| Item | Result |",
            "|------|--------|",
            f"| CUI Present in Environment | {'✅ YES' if cui else '❌ NO'} |",
            f"| FCI Present in Environment | {'✅ YES' if fci else '❌ NO'} |",
            f"| **CMMC Level Required** | **{level}** |",
            f"| Estimated Systems In Scope | {systems} |",
            f"| CUI Enclave Recommended | {'⚠️ YES — See Section 5' if enclave else '✅ Not Required'} |",
            f"| Scope Reduction Possible | {'✅ YES' if reduce else '➖ Not Applicable'} |",
            f"| Compliance Gaps Identified | {len(gaps)} total ({len(hi_gaps)} HIGH priority) |",
            "",
        ]

        if not cui and not fci:
            lines += [
                "> **Note:** Based on your responses, CUI/FCI may not be present in your environment.",
                "> However, you should verify this with your Contracting Officer (CO) and review your",
                "> contract for DFARS clauses 252.204-7012 and 252.204-7021 before concluding no",
                "> CMMC requirements apply.",
                "",
            ]

        # ── Section 1: Scope Determination ────────────────────────────────────
        lines += [
            "---",
            "",
            "## Section 1: CMMC Scope Determination",
            "",
            "### 1.1 Does CUI Exist in Your Environment?",
            "",
        ]

        if cui:
            cui_cats = self.flat.get("df_03", [])
            lines += [
                "**Result: YES — CUI is confirmed in scope.**",
                "",
                "Your organization handles Controlled Unclassified Information (CUI) that triggers",
                "CMMC Level 2 requirements under DFARS 252.204-7012 and the CMMC Final Rule (32 C.F.R. Part 170).",
                "",
                "**CUI Categories Identified:**",
                "",
            ]
            if isinstance(cui_cats, list):
                for cat in cui_cats:
                    lines.append(f"- {cat}")
            lines.append("")
        else:
            lines += [
                "**Result: CUI presence not confirmed based on responses.**",
                "",
                "Review your contract documentation to verify whether CUI is involved.",
                "",
            ]

        lines += ["### 1.2 Does FCI Exist in Your Environment?", ""]
        if fci:
            lines += [
                "**Result: YES — Federal Contract Information (FCI) is present.**",
                "",
                "FCI requires CMMC Level 1 compliance at minimum (basic cyber hygiene).",
                "",
            ]

        # ── Section 2: Asset Inventory Summary ────────────────────────────────
        lines += [
            "---",
            "",
            "## Section 2: Asset Inventory Summary",
            "",
            f"- **Total Computing Devices:** {self.flat.get('si_01', 'Not provided')}",
            f"- **Cloud Services Used:** {'Yes' if self.flat.get('si_02') else 'No'}",
        ]
        cloud_platforms = self.flat.get("si_02a", [])
        if cloud_platforms:
            lines.append(f"- **Cloud Platforms:** {', '.join(cloud_platforms) if isinstance(cloud_platforms, list) else cloud_platforms}")
        lines += [
            f"- **BYOD (Personal Devices):** {'Yes — review required' if self.flat.get('si_04') else 'No'}",
            f"- **Third-Party / Vendor Access:** {'Yes' if self.flat.get('si_08') else 'No'}",
            f"- **Asset Inventory Documented:** {'Yes' if self.flat.get('si_05') else '⚠️ No — Required by CM.2.062'}",
            f"- **Network Diagrams Available:** {'Yes' if self.flat.get('si_09') else '⚠️ No — Required for SSP'}",
            "",
        ]

        # ── Section 3: Boundary Definition ────────────────────────────────────
        lines += [
            "---",
            "",
            "## Section 3: Assessment Boundary Definition",
            "",
            f"- **Entire Environment In Scope:** {'Yes' if self.flat.get('bd_01') else 'No — boundary can be defined'}",
            f"- **Network Segmentation:** {self.flat.get('bd_02', 'Not assessed')}",
            f"- **Existing CUI Enclave:** {'Yes' if self.flat.get('bd_03') else 'No'}",
            f"- **Shared Services Spanning Boundary:** {'Yes — see gaps' if self.flat.get('bd_06') else 'No'}",
            f"- **System Security Plan (SSP) Exists:** {'Yes' if self.flat.get('bd_07') else '⚠️ No — Required'}",
            f"- **SPRS Score Submitted:** {'Yes' if self.flat.get('bd_08') else '⚠️ No — Required'}",
        ]
        if self.flat.get("bd_08a"):
            lines.append(f"- **Current SPRS Score:** {self.flat.get('bd_08a')}")
        lines.append("")

        # ── Section 4: Compliance Gaps ─────────────────────────────────────────
        lines += [
            "---",
            "",
            "## Section 4: Identified Compliance Gaps",
            "",
        ]

        if not gaps:
            lines += [
                "No significant compliance gaps were identified based on your responses.",
                "Note that a formal C3PAO assessment may identify additional gaps.",
                "",
            ]
        else:
            lines += [
                f"**{len(gaps)} compliance gaps identified** ({len(hi_gaps)} HIGH priority).",
                "",
                "| Priority | NIST Control | Gap Title |",
                "|----------|-------------|-----------|",
            ]
            for g in sorted(gaps, key=lambda x: 0 if x["priority"] == "HIGH" else 1):
                icon = "🔴" if g["priority"] == "HIGH" else "🟡"
                lines.append(f"| {icon} {g['priority']} | `{g['nist_control']}` | {g['title']} |")
            lines.append("")

            lines.append("### Gap Details\n")
            for i, g in enumerate(sorted(gaps, key=lambda x: 0 if x["priority"] == "HIGH" else 1), 1):
                icon = "🔴" if g["priority"] == "HIGH" else "🟡"
                lines += [
                    f"#### Gap {i}: {g['title']}",
                    f"- **Priority:** {icon} {g['priority']}",
                    f"- **NIST Control:** `{g['nist_control']}`",
                    f"- **Detail:** {g['detail']}",
                    "",
                ]

        # ── Section 5: Enclave Recommendation ─────────────────────────────────
        lines += [
            "---",
            "",
            "## Section 5: Enclave Architecture Recommendation",
            "",
        ]

        if enclave:
            lines += [
                "### ⚠️ CUI Enclave Recommended",
                "",
                "Based on your assessment, implementing a dedicated CUI enclave is strongly recommended.",
                "An enclave isolates all CUI processing to a defined, controlled environment, enabling",
                "you to apply CMMC controls only to enclave systems — significantly reducing compliance scope.",
                "",
                "**Benefits of the Docker CUI Enclave (this toolkit):**",
                "",
                "- Runs on existing commodity Linux hardware — no new hardware required",
                "- Complete network isolation via Docker networking and iptables",
                "- Pre-configured with auditd logging for NIST AU controls",
                "- Encrypted VPN gateway (WireGuard) for remote CUI access",
                "- Hardening scripts for the Linux host aligned to CMMC requirements",
                "- Free and open-source — no licensing fees",
                "",
                "**Next Steps:**",
                "",
                "1. Review [docs/architecture.md](../docs/architecture.md) for enclave design details",
                "2. Follow [docs/deployment-guide.md](../docs/deployment-guide.md) to deploy the enclave",
                "3. Run `enclave/scripts/host_harden.sh` to harden your Linux host",
                "4. Run `enclave/scripts/verify_controls.sh` to verify NIST control implementation",
                "",
            ]
        else:
            if self.flat.get("bd_03"):
                lines += [
                    "### ✅ CUI Enclave Already in Place",
                    "",
                    f"Your organization uses an existing enclave ({self.flat.get('bd_03a', 'type not specified')}).",
                    "Ensure your enclave is properly documented in your SSP and that its controls",
                    "are aligned to NIST SP 800-171 requirements.",
                    "",
                ]
            else:
                lines += [
                    "### ➖ Enclave Not Required Based on Current Assessment",
                    "",
                    "Based on your responses, an enclave may not be required. Verify this conclusion",
                    "with a qualified CMMC practitioner before your formal assessment.",
                    "",
                ]

        # ── Section 6: NIST Control Gap Summary ───────────────────────────────
        if ctrl_gaps:
            lines += [
                "---",
                "",
                "## Section 6: NIST SP 800-171 Control Gaps Summary",
                "",
                "The following NIST SP 800-171 control areas have potential gaps requiring remediation:",
                "",
            ]
            for ctrl in ctrl_gaps:
                lines.append(f"- `{ctrl}`")
            lines += [
                "",
                "See the [NIST SP 800-171 Rev 3](https://csrc.nist.gov/publications/detail/sp/800-171/rev-3/final)",
                "for full control requirements.",
                "",
            ]

        # ── Section 7: Recommended Next Steps ─────────────────────────────────
        lines += [
            "---",
            "",
            "## Section 7: Recommended Next Steps",
            "",
            "| Priority | Action |",
            "|----------|--------|",
            "| 1 | Address all HIGH priority gaps identified in Section 4 |",
            "| 2 | Develop or update your System Security Plan (SSP) |",
            "| 3 | Submit your NIST SP 800-171 self-assessment score to SPRS |",
        ]
        if enclave:
            lines.append("| 4 | Deploy the Docker CUI enclave to reduce CMMC assessment scope |")
        lines += [
            "| 5 | Engage a Registered Practitioner Organization (RPO) for gap remediation assistance |",
            "| 6 | Engage a C3PAO for formal CMMC Level 2 certification assessment |",
            "",
            "---",
            "",
            "*Report generated by CMMC Enclave Toolkit v1.0.0*",
            "*https://github.com/yourusername/cmmc-enclave-toolkit*",
            f"*Generated: {date_str}*",
        ]

        return "\n".join(lines)

    def save_markdown(self, path: str):
        Path(path).parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w") as f:
            f.write(self.generate_markdown())
